// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DataVault
{
	public partial class VaultTabController : UITabBarController
	{
		public VaultTabController (IntPtr handle) : base (handle)
		{
		}

		public VaultTabController()
		{
		}

		public AppDelegate appDelegate
		{
			get
			{
				return (AppDelegate)UIApplication.SharedApplication.Delegate;
			}
		}

		public override void ViewDidLoad()
		{
			this.appDelegate.navItem = this.NavigationItem;
			this.View.BackgroundColor = UIColor.White;

			this.TabBar.BarStyle = UIBarStyle.Default;

			appDelegate.tabBar = this.TabBar;

			SettingsController settings = new SettingsController();
			NotesController notes = new NotesController();

			this.SetViewControllers(new UIViewController[] { notes, settings }, true);

			this.TabBar.Items[0].Title = "My Diary";
			this.TabBar.Items[1].Title = "Settings";

			this.TabBar.SelectedImageTintColor = UIColor.Red;

			this.TabBar.Items[0].Image = new UIImage("PhrasesIcon.png");
			this.TabBar.Items[1].Image = new UIImage("SettingsUnselected2.png");

			if(UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Pad) {
				this.TabBar.ItemWidth = 300.0f;	
			}

			this.NavigationItem.Title = "My Diary";
			this.ViewControllerSelected += (object sender, UITabBarSelectionEventArgs e) =>
			{
				switch (this.SelectedIndex)
				{
					case 0: //vault controller
						this.NavigationItem.Title = "My Diary";
						this.NavigationItem.SetLeftBarButtonItem(this.appDelegate.editingBegan, false);
						this.NavigationItem.SetRightBarButtonItem(this.appDelegate.addButton, false);
						break;
					default:  //settings controller
						this.NavigationItem.Title = "Settings";
						UIBarButtonItem barNull = new UIBarButtonItem("", UIBarButtonItemStyle.Bordered, null);
						this.NavigationItem.SetLeftBarButtonItem(barNull, false);
						this.NavigationItem.SetRightBarButtonItem(barNull, false);
						break;
				}
			};
		}
	}
}
